### ISSUE TITLE
Should tempfile() ensure that its file is created in the same directory as the target?

### ISSUE THREAD

**Issue by FGasper** [perlancar/perl-File-Slurper-Temp#1]
It would seem advantageous for the write logic to ensure that the temp file exists alongside the target path, which should avoid EXDEV on the rename.

**Comment by perlancar** [comment]
Yes, I think that's a good default. I have changed (commit 5a8476b) the behavior of the write_text and write_binary functions to create temporary file in the same directory as target $filename. Thanks.
